# It's signifies that it is a YAML file
---
# Name that will appear in GitHub actions
name: Checks

# It's a trigger - this action will run on push (when we push something to the github)
on: [push]

# It's defines new job called test-lint
# name - the name of the action we will see in GitHub actions interface
# runs-on - the operating system used to run the job
# steps - the difference things that run for the job. Steps are executed in order

# name: - the name of the step, it will be visible in the GitHub actions interface
# uses: - use already created action that's provided in the GitHub actions repository


jobs:
  test-lint:
    name: Test and Lint
    # Docker composed is pre-installed in the container
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        # The command that runs unit test on our project
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"